### ISSUE TITLE
Key Actions with held keys are intermittently problematic on Windows with Kaldi engine

### ISSUE THREAD

**Issue by daanzu** [dictation-toolbox/dragonfly#182]
This spec used to work, but recently, started instead typing a plain `p` instead of with `ctrl` held. Removing the outer pause, "c-p" still seems to work fine.

**Comment by daanzu** [comment]
More strangeness: `Key("ctrl:down/200") + Mouse("left/200") + Key("ctrl:up")` seems to operate as if ctrl isn't held, but separate actions performed with separate voice commands work as intended (tested in chrome BTW). This used to work fine until recently.

**Comment by Danesprite** [comment]
Thanks for reporting this. I haven't tried to reproduce it yet, but I suspect this is related to #122.

**Comment by Danesprite** [comment]
I am unable to reproduce these problems on Windows 7. I'm testing by control clicking desktop icons and trying to print with `Key("c-p/10")` in Notepad. Can you please tell me what OS and Python version you are using and what applications you are testing with?

Also, are you running the current version of dragonfly (`master`)?

**Comment by daanzu** [comment]
I have been testing on py2.7 and Windows10. The `c-p` problem was in Sublime Merge; the mouse one in Chrome. It is pretty much `master`. I will test some more.

**Comment by daanzu** [comment]
Hmm, now i have both working, but not sure what fixed it. Investigating.

**Comment by Danesprite** [comment]
That is strange. Do you swap between keyboard layouts at all?

**Comment by daanzu** [comment]
Nope, always the standard en-us layout. It is very perplexing. The problem occurs in my normal setup with a vendored dragonfly, and doesn't occur in my dragonfly checkout. Both using the same virtual environment. Diff shows very few differences, none of which should be remotely related to these actions.

**Comment by Danesprite** [comment]
That is indeed perplexing. Does the problem consistently occur in your normal setup or only sometimes?

**Comment by daanzu** [comment]
Well, it was completely consistent: problems in one setup, and none in the other. But then, it inexplicably resolved itself. I'm not sure what changed. Mysterious, but I guess I'll close for now. 🤞

**Comment by Danesprite** [comment]
Huh. Mysterious.. Feel free to reopen if the problem occurs again.

**Comment by daanzu** [comment]
Okay, I appear to have a genuine Heisenbug. I finally turned off logging of `action.exec`, and it came back immediately. I have narrowed it down to [this logging line](https://github.com/dictation-toolbox/dragonfly/blob/2046550ee67519e28570244d3d347d89235e1840/dragonfly/actions/action_base.py#L89). If it is enabled, no problems. If it is disabled or commented out, almost always problems described above.

Clearly some kind of timing issue. However, simply adding a `time.sleep(1)` or any other numbers don't seem to fix it, so I am guessing the output to the console is affecting the timing elsewhere. Any ideas?

**Comment by Danesprite** [comment]
Heisenbug! I like that. Thanks for tracking it down. Very strange that a logging line is causing the problem. I'll have a look into this soon. I'd also like to check if the problem occurs under X11.

**Comment by Danesprite** [comment]
@daanzu I still haven't been able to reproduce this bug, even with the logging changes you mentioned above and in the linked issue.

Do you know if the problem occurs if you use actions like `Key("c-p/10")` from the REPL or with WSR? Just wondering if it's something to do with Kaldi. Unfortunately, I can't test with Kaldi on Windows at the moment.

**Comment by Danesprite** [comment]
It just occurred to me that modifier issues like this one could be caused by this code in `Win32Window.set_foreground()`:
https://github.com/dictation-toolbox/dragonfly/blob/b2f63bc4e58c8a110b8e4ceedcc97b2302ff386a/dragonfly/windows/win32_window.py#L234-L237

I'll change that method to use [`GetKeyState()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeystate) to check whether the key is currently being held down. If it is, then that code can just be skipped.

**Comment by daanzu** [comment]
I keep meaning to go back and test this more, but haven't yet. I have been lazy and just left in the logging, which bizarrely (temporarily) fixed it.

I can't remember if it was happening under WSR or not. I don't think I tested with REPL, but that is a good idea. I will try it after you put in that Window fix you just mentioned.

**Comment by Danesprite** [comment]
Okay then. I still have no idea why that logging change works for you!

I've fixed the control key bug in PR #213, although it might not be what's causing this issue. Let me know how the testing goes.

**Comment by daanzu** [comment]
Ha, yeah, it's pretty crazy. I will give it some more testing and let you know.

**Comment by Danesprite** [comment]
So this elusive Heisenbug is apparently still an issue. It was reported as recently as last month (August) in the Caster Gitter: https://gitter.im/dictation-toolbox/Caster?at=5f3fd61e48237809373379a8

Given that this bug only started occurring in December after the Win32 keyboard changes introduced in release versions 0.19.0 and 0.19.1, I reckon there must be some connection.

**Comment by daanzu** [comment]
I can believe that, but just reverting those changes alone didn't fix it for me back when I could produce the problem (at least as I recall -- can't retest).

**Comment by LexiconCode** [comment]
If you guys can come up with reasonable standalone test case that could be distributed to Windows kaldi end-users I could facilitate finding individuals. Perhaps from there we can coordinate efforts from testing to even a 1st look into their system.

**Comment by Danesprite** [comment]
Thanks @LexiconCode. Neither @daanzu nor myself really know what is going on here. I will try to reproduce the bug again soon.

**Comment by daanzu** [comment]
@LexiconCode If you have someone who can reproduce it, I do have a relatively simple idea to try that I didn't get a chance to try during the brief time I could reproduce it.

**Comment by Danesprite** [comment]
Dragonfly mostly uses scan codes for keyboard input emulation, which are hardware-dependent. I wonder if this problem is caused by a combination of this, use of certain keyboard models and Dragonfly's incorrect handling of extended keys, which may or may not include the control key depending on the hardware.

The incorrect handling of extended keys is fixed on the master branch (see #343) and will be fixed in the next Minor release version.

Given these things, perhaps the logging fix should be removed in a future release and we can see if the problem is still present? If it is, affected users can downgrade or wait for the logging fix to be reintroduced in a patch release version.

On a related note, it might be useful to add a Windows-only keyboard input emulation setting for always falling back on input via virtual-key codes instead of scan codes.

**Comment by daanzu** [comment]
@Danesprite You know more than I about the crazy intricacies of windows input, so I defer to your judgment. (All your work on it is appreciated!) All I can say is I have been unable to reproduce the problem for the past year and a half, and I run my own system with that logging fix disabled at all times in an attempt to catch it happening again, to no avail. Perhaps it was related to some internal thing in windows that has since been changed in a windows update. You could always disable the logging work around behind a feature flag to be safe.

**Comment by LexiconCode** [comment]
I would be in favor of a feature flag. That way we don't have to wait to another release and I can get a handle on how much this exists in the caster community.

**Comment by Danesprite** [comment]
Okay then. It's a shame you haven't been able to replicate this, @daanzu. Thanks for trying. I think it is more likely this was caused by Dragonfly's input code, but you may be right; it might have been some Windows bug.

I will leave the logging work around in a `KaldiEngine` method that users can call. I have done something similar for the Natlink back-end. That would be helpful, @LexiconCode. Keep us posted. :-)

**Comment by Danesprite** [comment]
The `KaldiEngine` method to enable the fix is `_apply_win32_kb_input_logging_fix()`.

I'd like to close this issue and reopen it if I see a report of the problem. Feel free to do the same, @LexiconCode. No news would be good news. :-)
